-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC import sys
-- MAGIC
-- MAGIC sys.path.append("/Workspace/Users/swapniltake1@outlook.com/New Pipeline 2025-12-31 16:45-(1)")

-- COMMAND ----------

SHOW TABLES IN bankof420.bank_infrastructure;

-- COMMAND ----------

CREATE OR REFRESH STREAMING TABLE bankof420.bank_infrastructure.atm_locations
AS SELECT * FROM bankof420.bank_infrastructure.source_atm_locations;

-- COMMAND ----------

CREATE OR REFRESH STREAMING TABLE bankof420.bank_infrastructure.branches
AS SELECT * FROM bankof420.bank_infrastructure.source_branches;
